//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UseridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Userid {
            get {
                return this.UseridField;
            }
            set {
                if ((this.UseridField.Equals(value) != true)) {
                    this.UseridField = value;
                    this.RaisePropertyChanged("Userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item_Info", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.SerializableAttribute()]
    public partial class Item_Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPIRYDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemImgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPIRYDATE {
            get {
                return this.EXPIRYDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPIRYDATEField, value) != true)) {
                    this.EXPIRYDATEField = value;
                    this.RaisePropertyChanged("EXPIRYDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long barcode {
            get {
                return this.barcodeField;
            }
            set {
                if ((this.barcodeField.Equals(value) != true)) {
                    this.barcodeField = value;
                    this.RaisePropertyChanged("barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemImg {
            get {
                return this.itemImgField;
            }
            set {
                if ((object.ReferenceEquals(this.itemImgField, value) != true)) {
                    this.itemImgField = value;
                    this.RaisePropertyChanged("itemImg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NUTRITION_METER", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.SerializableAttribute()]
    public partial class NUTRITION_METER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CarbohydrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FibreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ItemBarcodeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SaturatedFatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SodiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SugarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Carbohydrate {
            get {
                return this.CarbohydrateField;
            }
            set {
                if ((this.CarbohydrateField.Equals(value) != true)) {
                    this.CarbohydrateField = value;
                    this.RaisePropertyChanged("Carbohydrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Fibre {
            get {
                return this.FibreField;
            }
            set {
                if ((this.FibreField.Equals(value) != true)) {
                    this.FibreField = value;
                    this.RaisePropertyChanged("Fibre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ItemBarcodeNo {
            get {
                return this.ItemBarcodeNoField;
            }
            set {
                if ((this.ItemBarcodeNoField.Equals(value) != true)) {
                    this.ItemBarcodeNoField = value;
                    this.RaisePropertyChanged("ItemBarcodeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float SaturatedFat {
            get {
                return this.SaturatedFatField;
            }
            set {
                if ((this.SaturatedFatField.Equals(value) != true)) {
                    this.SaturatedFatField = value;
                    this.RaisePropertyChanged("SaturatedFat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Sodium {
            get {
                return this.SodiumField;
            }
            set {
                if ((this.SodiumField.Equals(value) != true)) {
                    this.SodiumField = value;
                    this.RaisePropertyChanged("Sodium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Sugar {
            get {
                return this.SugarField;
            }
            set {
                if ((this.SugarField.Equals(value) != true)) {
                    this.SugarField = value;
                    this.RaisePropertyChanged("Sugar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calorie_Calculator", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.SerializableAttribute()]
    public partial class Calorie_Calculator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Extra_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Lightly_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Moderatetely_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SedentaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Very_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double bmrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Extra_active {
            get {
                return this.Extra_activeField;
            }
            set {
                if ((this.Extra_activeField.Equals(value) != true)) {
                    this.Extra_activeField = value;
                    this.RaisePropertyChanged("Extra_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lightly_active {
            get {
                return this.Lightly_activeField;
            }
            set {
                if ((this.Lightly_activeField.Equals(value) != true)) {
                    this.Lightly_activeField = value;
                    this.RaisePropertyChanged("Lightly_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Moderatetely_active {
            get {
                return this.Moderatetely_activeField;
            }
            set {
                if ((this.Moderatetely_activeField.Equals(value) != true)) {
                    this.Moderatetely_activeField = value;
                    this.RaisePropertyChanged("Moderatetely_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Sedentary {
            get {
                return this.SedentaryField;
            }
            set {
                if ((this.SedentaryField.Equals(value) != true)) {
                    this.SedentaryField = value;
                    this.RaisePropertyChanged("Sedentary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USERID {
            get {
                return this.USERIDField;
            }
            set {
                if ((this.USERIDField.Equals(value) != true)) {
                    this.USERIDField = value;
                    this.RaisePropertyChanged("USERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Very_active {
            get {
                return this.Very_activeField;
            }
            set {
                if ((this.Very_activeField.Equals(value) != true)) {
                    this.Very_activeField = value;
                    this.RaisePropertyChanged("Very_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double bmr {
            get {
                return this.bmrField;
            }
            set {
                if ((this.bmrField.Equals(value) != true)) {
                    this.bmrField = value;
                    this.RaisePropertyChanged("bmr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe_List", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.SerializableAttribute()]
    public partial class Recipe_List : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPIRYDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEMNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ingredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPIRYDATE {
            get {
                return this.EXPIRYDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPIRYDATEField, value) != true)) {
                    this.EXPIRYDATEField = value;
                    this.RaisePropertyChanged("EXPIRYDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEMNAME {
            get {
                return this.ITEMNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMNAMEField, value) != true)) {
                    this.ITEMNAMEField = value;
                    this.RaisePropertyChanged("ITEMNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipename {
            get {
                return this.RecipenameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipenameField, value) != true)) {
                    this.RecipenameField = value;
                    this.RaisePropertyChanged("Recipename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ingredients {
            get {
                return this.ingredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ingredientsField, value) != true)) {
                    this.ingredientsField = value;
                    this.RaisePropertyChanged("ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserId", ReplyAction="http://tempuri.org/IService1/GetUserIdResponse")]
        Gp.ServiceReference1.User[] GetUserId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserId", ReplyAction="http://tempuri.org/IService1/GetUserIdResponse")]
        System.Threading.Tasks.Task<Gp.ServiceReference1.User[]> GetUserIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        void GetImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task GetImageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        int Register(string name, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(string name, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserId", ReplyAction="http://tempuri.org/IService1/AddUserIdResponse")]
        int AddUserId(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserId", ReplyAction="http://tempuri.org/IService1/AddUserIdResponse")]
        System.Threading.Tasks.Task<int> AddUserIdAsync(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOfBarcodes", ReplyAction="http://tempuri.org/IService1/ListOfBarcodesResponse")]
        Gp.ServiceReference1.Item_Info[] ListOfBarcodes(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOfBarcodes", ReplyAction="http://tempuri.org/IService1/ListOfBarcodesResponse")]
        System.Threading.Tasks.Task<Gp.ServiceReference1.Item_Info[]> ListOfBarcodesAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBarcode", ReplyAction="http://tempuri.org/IService1/AddBarcodeResponse")]
        string AddBarcode(string email, string password, long barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBarcode", ReplyAction="http://tempuri.org/IService1/AddBarcodeResponse")]
        System.Threading.Tasks.Task<string> AddBarcodeAsync(string email, string password, long barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveBarcode", ReplyAction="http://tempuri.org/IService1/RemoveBarcodeResponse")]
        string RemoveBarcode(string email, string password, long barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveBarcode", ReplyAction="http://tempuri.org/IService1/RemoveBarcodeResponse")]
        System.Threading.Tasks.Task<string> RemoveBarcodeAsync(string email, string password, long barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        int GetUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<int> GetUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOfNutritions", ReplyAction="http://tempuri.org/IService1/ListOfNutritionsResponse")]
        Gp.ServiceReference1.NUTRITION_METER[] ListOfNutritions(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOfNutritions", ReplyAction="http://tempuri.org/IService1/ListOfNutritionsResponse")]
        System.Threading.Tasks.Task<Gp.ServiceReference1.NUTRITION_METER[]> ListOfNutritionsAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCalories", ReplyAction="http://tempuri.org/IService1/SetCaloriesResponse")]
        Gp.ServiceReference1.Calorie_Calculator SetCalories(string email, string password, int age, string gender, float height, float weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCalories", ReplyAction="http://tempuri.org/IService1/SetCaloriesResponse")]
        System.Threading.Tasks.Task<Gp.ServiceReference1.Calorie_Calculator> SetCaloriesAsync(string email, string password, int age, string gender, float height, float weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecipes", ReplyAction="http://tempuri.org/IService1/GetRecipesResponse")]
        Gp.ServiceReference1.Recipe_List[] GetRecipes(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecipes", ReplyAction="http://tempuri.org/IService1/GetRecipesResponse")]
        System.Threading.Tasks.Task<Gp.ServiceReference1.Recipe_List[]> GetRecipesAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Gp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Gp.ServiceReference1.IService1>, Gp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gp.ServiceReference1.User[] GetUserId() {
            return base.Channel.GetUserId();
        }
        
        public System.Threading.Tasks.Task<Gp.ServiceReference1.User[]> GetUserIdAsync() {
            return base.Channel.GetUserIdAsync();
        }
        
        public void GetImage() {
            base.Channel.GetImage();
        }
        
        public System.Threading.Tasks.Task GetImageAsync() {
            return base.Channel.GetImageAsync();
        }
        
        public int Register(string name, string email, string password) {
            return base.Channel.Register(name, email, password);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string name, string email, string password) {
            return base.Channel.RegisterAsync(name, email, password);
        }
        
        public int AddUserId(int user_id) {
            return base.Channel.AddUserId(user_id);
        }
        
        public System.Threading.Tasks.Task<int> AddUserIdAsync(int user_id) {
            return base.Channel.AddUserIdAsync(user_id);
        }
        
        public Gp.ServiceReference1.Item_Info[] ListOfBarcodes(string email, string password) {
            return base.Channel.ListOfBarcodes(email, password);
        }
        
        public System.Threading.Tasks.Task<Gp.ServiceReference1.Item_Info[]> ListOfBarcodesAsync(string email, string password) {
            return base.Channel.ListOfBarcodesAsync(email, password);
        }
        
        public string Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string AddBarcode(string email, string password, long barcode) {
            return base.Channel.AddBarcode(email, password, barcode);
        }
        
        public System.Threading.Tasks.Task<string> AddBarcodeAsync(string email, string password, long barcode) {
            return base.Channel.AddBarcodeAsync(email, password, barcode);
        }
        
        public string RemoveBarcode(string email, string password, long barcode) {
            return base.Channel.RemoveBarcode(email, password, barcode);
        }
        
        public System.Threading.Tasks.Task<string> RemoveBarcodeAsync(string email, string password, long barcode) {
            return base.Channel.RemoveBarcodeAsync(email, password, barcode);
        }
        
        public int GetUser(string email, string password) {
            return base.Channel.GetUser(email, password);
        }
        
        public System.Threading.Tasks.Task<int> GetUserAsync(string email, string password) {
            return base.Channel.GetUserAsync(email, password);
        }
        
        public Gp.ServiceReference1.NUTRITION_METER[] ListOfNutritions(string email, string password) {
            return base.Channel.ListOfNutritions(email, password);
        }
        
        public System.Threading.Tasks.Task<Gp.ServiceReference1.NUTRITION_METER[]> ListOfNutritionsAsync(string email, string password) {
            return base.Channel.ListOfNutritionsAsync(email, password);
        }
        
        public Gp.ServiceReference1.Calorie_Calculator SetCalories(string email, string password, int age, string gender, float height, float weight) {
            return base.Channel.SetCalories(email, password, age, gender, height, weight);
        }
        
        public System.Threading.Tasks.Task<Gp.ServiceReference1.Calorie_Calculator> SetCaloriesAsync(string email, string password, int age, string gender, float height, float weight) {
            return base.Channel.SetCaloriesAsync(email, password, age, gender, height, weight);
        }
        
        public Gp.ServiceReference1.Recipe_List[] GetRecipes(string email, string password) {
            return base.Channel.GetRecipes(email, password);
        }
        
        public System.Threading.Tasks.Task<Gp.ServiceReference1.Recipe_List[]> GetRecipesAsync(string email, string password) {
            return base.Channel.GetRecipesAsync(email, password);
        }
    }
}
